@OrderManagementAPI_HostAddress = http://localhost:5114/api


# CUSTOMER
GET {{OrderManagementAPI_HostAddress}}/customers
Accept: application/json
###

POST {{OrderManagementAPI_HostAddress}}/customers
Content-Type: application/json
Accept: application/json
{
  "name": "George",
  "email": "george@example.com",
  "address": "Tbilisi"
}
###




# PRODUCT
### Get all products
GET {{OrderManagementAPI_HostAddress}}/products
Accept: application/json

### Get product by ID
GET {{OrderManagementAPI_HostAddress}}/products/1
Accept: application/json

### Create a new product
POST {{OrderManagementAPI_HostAddress}}/products
Content-Type: application/json

{
  "name": "Laptop1",
  "price": 1100.00,
  "description": "with 16GB RAM"
}

### Update an existing product
PUT {{OrderManagementAPI_HostAddress}}/products/1
Content-Type: application/json

{
  "id": 1,
  "name": "Laptop Pro",
  "price": 1500.00,
  "description": "Upgraded model with 32GB RAM"
}

### Delete a product
DELETE {{OrderManagementAPI_HostAddress}}/products/1
###





# ORDER
### Get all orders
GET {{OrderManagementAPI_HostAddress}}/orders
Accept: application/json

### Get order by ID
GET {{OrderManagementAPI_HostAddress}}/orders/1
Accept: application/json

### Create a new order
POST {{OrderManagementAPI_HostAddress}}/orders
Content-Type: application/json

{
  "customerId": 1,
  "orderDate": "2026-02-17T16:35:00",
  "status": "Pending",
  "items": [
    {
      "productId": 2,
      "quantity": 3
    }
  ]
}

### Update an existing order
PUT {{OrderManagementAPI_HostAddress}}/orders/1
Content-Type: application/json

{
  "id": 1,
  "customerId": 1,
  "orderDate": "2026-02-17T16:45:00",
  "status": "Shipped",
  "items": [
    {
      "productId": 2,
      "quantity": 5
    }
  ]
}

### Delete an order
DELETE {{OrderManagementAPI_HostAddress}}/orders/1